version: 1.{build}
  
image: Visual Studio 2022

environment:
  TARGET_CONFIGURATION: Release

platform: Any CPU

branches:
  only:
    - master

only_commits:
  message: /build/
#  files:
#    - src/*

before_build:
- cmd: >-
    dotnet --version

    dotnet restore

build_script:
- cmd: >-
    dotnet pack .\src\WeChatApi.Abstractions -c %TARGET_CONFIGURATION%

    dotnet pack .\src\WeChatApi.RestSharp -c %TARGET_CONFIGURATION%

artifacts:
  - path: "src/**/*.nupkg"
    name: "WeChatApi NuGet Packages"

deploy:
  - provider: NuGet
    api_key:
      secure: m281r1dMaWVDTd7j0coGCGUQDUBjgBuvmV1d9iD7ueI1AaME/Xx2t7GK3ox/z4UP
    artifact: /.*\.nupkg/
