version: '{build}'
  
environment:
  VERSION: 1.0.2
  TARGET_CONFIGURATION: Release

image: Visual Studio 2022

platform: Any CPU

branches:
  only:
    - master

only_commits:
  message: /(build|publish)/
#  files:
#    - src/*

before_build:
- cmd: >-
    dotnet --version

    dotnet restore

build_script:
- cmd: >-
    dotnet pack .\src\WeChatApi.Abstractions -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

    dotnet pack .\src\WeChatApi.RestSharp -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

artifacts:
  - path: "src/**/*.nupkg"
    name: "WeChatApi NuGet Packages"

deploy:
  - provider: NuGet
    api_key:
      secure: m281r1dMaWVDTd7j0coGCGUQDUBjgBuvmV1d9iD7ueI1AaME/Xx2t7GK3ox/z4UP
    artifact: /.*\.nupkg/
